<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'customer/customer/index'  => __DIR__ . '/customer/customer/index.phtml',
    'customer/customer/show'   => __DIR__ . '/customer/customer/show.phtml',
    'customer/customer/update' => __DIR__ . '/customer/customer/update.phtml',
    'customer/customer/create' => __DIR__ . '/customer/customer/create.phtml',
    'template_map'             => __DIR__ . '/template_map.php',
);
