<?php
/**
 * Zend Framework 2 Beispiel
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zendframeworkbuch.de/
 */

/**
 * Footer view script
 * 
 * @package    Application
 */

$url = $this->url(null, array(), true);
?>
<footer id="footer">
<div class="footer-top"></div>
<div class="container">
Hier steht dann der Footer
</div>
</div>
</footer>
